# Generated by Django 3.2.6 on 2021-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringform',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reviewform',
            name='id',
        ),
        migrations.AddField(
            model_name='cateringform',
            name='catering_form_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='contact_form_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reviewform',
            name='review_form_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
