# Generated by Django 3.2.6 on 2021-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_auto_20210810_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringform',
            name='catering_form_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact_form_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='review_form_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
