# Generated by Django 3.2.6 on 2021-08-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_auto_20210810_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringform',
            name='additional_hours',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='cateringform',
            name='package_type',
            field=models.CharField(blank=True, choices=[('The Lieutant', 'The Lieutant'), ('The Captain', 'The Captain'), ('The Sargeant', 'The Sargeant')], max_length=25),
        ),
        migrations.AddField(
            model_name='cateringform',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('VENMO', 'Venmo'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=25),
        ),
        migrations.AddField(
            model_name='contactform',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('QUESTION', 'Question'), ('FEEDBACK', 'Feedback'), ('CONCERN', 'Concern')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='food_rating',
            field=models.CharField(blank=True, choices=[(1, 'Not very good'), (2, 'Not good'), (3, 'OK'), (4, 'Good'), (5, 'Very good')], max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='service_rating',
            field=models.CharField(blank=True, choices=[(1, 'Not very good'), (2, 'Not good'), (3, 'OK'), (4, 'Good'), (5, 'Very good')], max_length=25),
        ),
    ]
