# Generated by Django 3.2.6 on 2021-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20210810_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringform',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cateringform',
            name='message',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='reviewform',
            name='review_message',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
