# Generated by Django 3.2.6 on 2021-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_auto_20210816_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='reviewform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
