# Generated by Django 3.2.6 on 2021-08-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.TextField(max_length=200, null=True)),
                ('badge_image', models.ImageField(upload_to='')),
                ('badge_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=200, null=True)),
                ('last_name', models.TextField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.TextField(max_length=200, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('Tax Document', 'Tax Document'), ('Legal Document', 'Legal Document'), ('State Document', 'State Document'), ('Federal Document', 'Federal Document'), ('Other Document', 'Other Document')], max_length=50)),
                ('document_file', models.FileField(null=True, upload_to='')),
                ('document_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('country', models.TextField(max_length=200, null=True)),
                ('role', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Founder', 'Founder'), ('Employee', 'Employee')], max_length=50)),
                ('schedule', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pay_rate', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type', models.CharField(blank=True, choices=[('Equipment', 'Equipment'), ('Smallware', 'Smallware'), ('Marketing', 'Marketing'), ('Product', 'Product'), ('Labor', 'Labor'), ('Utility', 'Utility'), ('Truck', 'Truck'), ('Misc', 'Misc')], max_length=50)),
                ('expense_cost', models.CharField(max_length=200, null=True)),
                ('expense_date', models.DateTimeField()),
                ('expense_message', models.CharField(max_length=1000, null=True)),
                ('expense_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('Food', 'Food'), ('Beverages', 'Beverages'), ('Sides', 'Sides'), ('Desserts', 'Desserts'), ('Non-Food', 'Non-Food')], max_length=50)),
                ('product_cost', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('digital_price', models.BooleanField(default=False, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=500, null=True)),
                ('recipe_type', models.CharField(blank=True, choices=[('Food Recipe', 'Food Recipe'), ('Drink Recipe', 'Drink Recipe'), ('Condiment Recipe', 'Condiment Recipe'), ('Other Recipe', 'Other Recipe')], max_length=50)),
                ('recipe_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_message', models.CharField(max_length=500, null=True)),
                ('task_date', models.DateTimeField()),
                ('task_added', models.DateTimeField(auto_now_add=True)),
                ('task_status', models.BooleanField(default=False)),
                ('task_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyapp.customer')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('inspection_reason', models.CharField(blank=True, choices=[('Equipment Inspection', 'Equipment Inspection'), ('Cleanliness Inspection', 'Cleanliness Inspection'), ('Food Temperature Inspection', 'Food Temperature Inspection'), ('Food Preparation Inspection', 'Food Preparation Inspection'), ('Food Storage Inspection', 'Food Storage Inspection'), ('Facility Setup Inspection', 'Facility Setup Inspection'), ('Pest Control Inspection', 'Pest Control Inspection')], max_length=50)),
                ('inspection_message', models.CharField(max_length=500, null=True)),
                ('inspection_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyapp.employee')),
            ],
        ),
    ]
