# Generated by Django 3.2.6 on 2021-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital_price',
            new_name='digital_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
